admin_controllers:
    resource: ../../src/Controller/Admin/
    type: annotation
    prefix: /admin

client_controllers:
    resource: ../../src/Controller/Client/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
