# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
#    App\:
#        resource: '../src/*'
#        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Repository\CategoryRepository:
        class: App\Repository\CategoryRepository
        arguments: ['@Doctrine\Persistence\ManagerRegistry']

    App\Repository\ProductRepository:
        class: App\Repository\ProductRepository
        arguments: [ '@Doctrine\Persistence\ManagerRegistry' ]
        
    App\Repository\ShopRepository:
        class: App\Repository\ShopRepository
        arguments: ['@Doctrine\Persistence\ManagerRegistry']

    App\Manager\ProductManager:
        class: App\Manager\ProductManager
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Symfony\Component\Routing\RouterInterface'
            - '%kernel.project_dir%/public/uploads'

    App\Security\AdminAuthenticator:
        class: App\Security\AdminAuthenticator
        arguments:
            - '@Symfony\Component\Routing\Generator\UrlGeneratorInterface'
            - '@Symfony\Component\Security\Csrf\CsrfTokenManagerInterface'
            - '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface'